name: suns
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.8
  - pip
  - numpy
  - h5py=2.10.0
  - matplotlib
  - numba
  - opencv
  - scikit-image
  - scikit-learn
  - scipy
  - shapely 
  # - tensorflow==1.15
  - tensorflow-gpu==1.15
  - keras
  - pip:
    - fissa==0.7.2
    - pyfftw
    - tensorflow-estimator==1.15.1
    - py-cpuinfo
