name: suns
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.8
  - pip
  - numpy
  - h5py
  - matplotlib
  - numba
  - opencv
  - scikit-image
  - scikit-learn
  - scipy
  - shapely 
  # - tensorflow ==2.1
  - tensorflow-gpu ==2.1
  - keras
  - pip:
    - fissa==0.7.2
    - pyfftw
    - tensorflow-estimator==2.1
    - py-cpuinfo
